# Generated by Django 3.2.8 on 2021-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('handler_memory', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(name='item', unique_together=set()),
        migrations.RemoveField(model_name='item', name='team_id'),
    ]
