# Generated by Django 4.2.30 on 2026-06-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slacker", "0005_add_workspace_fk"),
        ("handler_memory", "0002_auto_20211021_1536"),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, se: se.connection.vendor == 'mysql'
            and se.execute(
                "ALTER TABLE handler_memory_item CONVERT TO CHARACTER SET utf8mb4"
            ),
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="item",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slacker.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="key",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="item", unique_together={("workspace", "key")}
        ),
    ]
