# Generated by Django 4.0.8 on 2022-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('handler_loud', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        )
    ]
