# Generated by Django 4.2.30 on 2026-06-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slacker", "0005_add_workspace_fk"),
        ("handler_loud", "0002_alter_shout_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="shout",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slacker.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="shout",
            name="text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="shout", unique_together={("workspace", "text")}
        ),
    ]
