# Generated by Django 3.2.8 on 2021-10-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='team_id',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('team_id', 'name')},
        ),
    ]
