# Generated by Django 4.2.30 on 2026-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("slacker", "0003_auto_20211021_1536")]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "team_id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("team_name", models.CharField(max_length=255)),
                (
                    "enterprise_id",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("bot_token", models.CharField(max_length=255)),
                ("bot_id", models.CharField(max_length=32)),
                ("bot_user_id", models.CharField(max_length=32)),
                ("bot_scopes", models.TextField(default="")),
                ("installed_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
