# Generated by Django 4.2.30 on 2026-06-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [("slacker", "0004_workspace_model")]

    operations = [
        migrations.RunPython(
            lambda apps, se: se.connection.vendor == 'mysql'
            and se.execute(
                "ALTER TABLE slacker_channel CONVERT TO CHARACTER SET utf8mb4"
            ),
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="channel",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slacker.workspace",
            ),
        ),
    ]
