# Generated by Django 4.2.30 on 2026-06-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slacker", "0005_add_workspace_fk"),
        ("handler_responder", "0002_auto_20211020_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slacker.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="phrase",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="trigger", unique_together={("workspace", "phrase")}
        ),
    ]
