# Generated by Django 3.2.8 on 2021-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('handler_sparkles', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(name='user', unique_together=set()),
        migrations.RemoveField(model_name='user', name='team_id'),
    ]
