# Generated by Django 3.2.8 on 2021-10-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('handler_sparkles', '0002_auto_20211021_1536')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sparkles',
            field=models.IntegerField(db_index=True, default=0),
        )
    ]
