# Generated by Django 4.2.30 on 2026-06-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slacker", "0005_add_workspace_fk"),
        ("handler_sparkles", "0003_alter_user_sparkles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slacker.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name="user", unique_together={("workspace", "user_id")}
        ),
    ]
