# Generated by Django 4.2.30 on 2026-06-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slacker", "0005_add_workspace_fk"),
        ("handler_about", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="fact", unique_together=set()),
        migrations.AlterIndexTogether(name="fact", index_together=set()),
        migrations.AddField(
            model_name="fact",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slacker.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fact", unique_together={("workspace", "user_id", "value")}
        ),
        migrations.AlterIndexTogether(
            name="fact", index_together={("workspace", "user_id", "created_at")}
        ),
    ]
