name: simone
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Bootstrap
        run: |
          ./script/bootstrap
      - name: Lint, check formatting, & run tests
        run: |
          ./git_hooks_pre-commit
